# Uncomment this line to define a global platform for your project
# platform :ios, ‘8.0’

target 'JLFoods' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JLFoods
pod ‘AFNetworking’
pod ’SDWebImage’
pod ‘Masonry’
pod ’SVProgressHUD’
pod ‘JPFPSStatus’  
end
